const GITHUB_AUTH_TOKEN = "PRABATH-MD"
const BOT_NUMBER = "916001461599"
const SESSION_ID = "PRABATH-MD~jRkD3Q7Q#U0TDREu6Gbu7OofdvxXXu-iMUBHrCYGMVUWbUj43kIA"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
